# NumPy

Read the link https://numpy.org/doc/stable/user/quickstart.html before starting the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [3]:
A = np.arange(1, 16).reshape(3,5)
print(A)
print("Dimension (number of axes):", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Datatype:", A.dtype)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Dimension (number of axes): 2
Shape: (3, 5)
Size: 15
Datatype: int64


In [4]:
print("Dimension (number of axes):", A.ndim)
print("Shape:", A.shape)
print("Size:", A.size)
print("Datatype:", A.dtype)

Dimension (number of axes): 2
Shape: (3, 5)
Size: 15
Datatype: int64


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [5]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [6]:
print(B - C)
print(B * C)
print(B @ C)

[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on matrix D:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [7]:
D = np.arange(1, 10).reshape(3, 3)
print(D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [8]:
print(np.exp(D))
print(np.min(D))
print (np.min(D,1))
print (np.min(D,0))
print(np.argmin(D))
print(np.argmin(D, axis=1))
print(np.sum(D))
print(np.mean(D, axis=0))
print(np.median(D, axis=0))



[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
1
[1 4 7]
[1 2 3]
0
[0 0 0]
45
[4. 5. 6.]
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [9]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [10]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [11]:
# When i provide fewer indices than the array has dimensions, numpy returns a sub-array corresponding to the provided indices.
# In practice it means equivalent A[1, :] which is the second row.

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [12]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [14]:
for i in A.flatten():
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [15]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [16]:
# It means 3 dimensional array and third dimension is calcualted like the sum of the first and second number.
# What was mindblowing for me is that first number now indicating number of blocks while second and third indicated rows and columns.

### Broadcasting
Read the link https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting and the document *"matematik_yh_kap_10"* (solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh) before starting the exercises below.  

If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

##### Remark on Broadcasting when doing Linear Algebra calculations in Python. 
From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices.

In [17]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [18]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [19]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


### Vector and matrix algebra

Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.

Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).

In [ ]:
def add_mult_matrices(matrix1, matrix2, operation):
    # Validate that inputs are numpy arrays
    if not isinstance(matrix1, np.ndarray):
        raise TypeError("matrix1 must be a numpy.ndarray")
    if not isinstance(matrix2, np.ndarray):
        raise TypeError("matrix2 must be a numpy.ndarray")
    
    # Validate that operation is either 'add' or 'multiply'
    # Obs! Jag gav mig frigheten o lägga till 'subtract' om man ändå håller på så där, hoppas det är ok?!
    if operation not in ['add', 'multiply', 'subtract']:
        raise ValueError("operation must be either 'add' or 'multiply'")
    
    # Perform addition
    if operation == 'add':
        # Validate that matrices have the same shape
        if matrix1.shape != matrix2.shape:
            raise ValueError(f"Matrices must have the same shape for addition. Got {matrix1.shape} and {matrix2.shape}")
        return matrix1 + matrix2
    
        # Perform addition
    if operation == 'subtract':
        # Validate that matrices have the same shape
        if matrix1.shape != matrix2.shape:
            raise ValueError(f"Matrices must have the same shape for subtraction. Got {matrix1.shape} and {matrix2.shape}")
        return matrix1 - matrix2
    
    # Perform multiplication
    elif operation == 'multiply':
        # Validate that number of columns in matrix1 equals number of rows in matrix2
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError(f"Number of columns in matrix1 ({matrix1.shape[1]}) must equal number of rows in matrix2 ({matrix2.shape[0]})")
        return matrix1 @ matrix2

### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan" by using Python. Note, the function you created above can be used. 

In [79]:
print("10.1.1 from the book")
x = np.array([[4], [3]])
#10.1.1
print("a)")
print(x.ndim)
print("")

print("b)")
print((5*x))
print("")

print("c)")
print((3*x))
print("")

print("d)")
print(add_mult_matrices(5*x, 3*x, 'add'))
print("")

print("e)")
print(8*x)
print("")

print("f)")
print(4*x - x)
print("")

print("g)")
print(x.T)
print((x.T).ndim)
print("")

print("h)")
print(x + x.T)
print("no, its not defined/correct from the point of view of linear algebra, cause the shapes are different")

print("i)")
print(np.linalg.norm(x))
print("")




10.1.1 from the book
a)
2

b)
[[20]
 [15]]

c)
[[12]
 [ 9]]

d)
[[32]
 [24]]

e)
[[32]
 [24]]

f)
[[12]
 [ 9]]

g)
[[4 3]]
2

h)
[[8 7]
 [7 6]]
no, its not defined/correct from the point of view of linear algebra, cause the shapes are different
i)
5.0



In [84]:
print("10.1.2 from the book")
v = np.array([[3], [7], [0], [11]])

print("a)")
print(v.ndim)
print("")

print("b)")
print(2*v)
print("")

print("c)")
print(add_mult_matrices(5*v , 2*v, 'add'))
print("")

print("d)")
print(add_mult_matrices(4*v , 1*v, 'subtract'))
print("")

print("?)")
print()
print("")

10.1.2 from the book
a)
2

b)
[[ 6]
 [14]
 [ 0]
 [22]]

c)
[[21]
 [49]
 [ 0]
 [77]]

d)
[[ 9]
 [21]
 [ 0]
 [33]]

?)




### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan" by using Python. 

In [ ]:
print("10.2.4 from the book")
# Define the coefficient matrix A and the constants vector b
A = np.array([[3, 2, 4],
              [2, 3, 8],
              [4, 1, 3],
              [7, 1, 5]])

b = np.array([[7],
              [4],
              [11],
              [9]])

print("Coefficient matrix A:")
print(A)
print(f"Shape: {A.shape}")
print()

print("Constants vector b:")
print(b)
print(f"Shape: {b.shape}")
print()

# Solve using least squares (since we have more equations than unknowns)
# np.linalg.lstsq finds the least-squares solution
solution, residuals, rank, s = np.linalg.lstsq(A, b, rcond=None)

print("Solution (least squares):")
print(f"x₁ = {solution[0][0]:.6f}")
print(f"x₂ = {solution[1][0]:.6f}")
print(f"x₃ = {solution[2][0]:.6f}")
print()



10.2.4 from the book
Coefficient matrix A:
[[3 2 4]
 [2 3 8]
 [4 1 3]
 [7 1 5]]
Shape: (4, 3)

Constants vector b:
[[ 7]
 [ 4]
 [11]
 [ 9]]
Shape: (4, 1)

Solution (least squares):
x₁ = 2.136914
x₂ = 4.834123
x₃ = -1.891522



### Copies and Views
Read the link https://numpy.org/doc/stable/user/basics.copies.html before starting the exercises below. 

Basic indexing creates a view. How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?

In [ ]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [ ]:
# Check if v2 is a view or copy
print("How to check if v2 is a view or copy:")
print("1. Check if v2.base is v1:", v2.base is v1)
print("2. v2 shares memory with v1:", np.shares_memory(v1, v2))
print()

# Change the last element in v2 to 123
print("Changing last element in v2 to 123...")
v2[-1] = 123
print()

print("After modification:")
print("v1:", v1)
print("v2:", v2)
print()

print("Answer:")
print("Yes, the last element in v1 is also changed to 123.")
print("Why? Because v2 is a VIEW of v1, not a copy.")
print("Basic indexing (slicing) creates a view that points to the same memory.")
print("When you modify v2, you're modifying the underlying data that v1 also references.")

How to check if v2 is a view or copy:
1. Check if v2.base is v1: True
2. v2 shares memory with v1: True

Changing last element in v2 to 123...

After modification:
v1: [  0   1   2 123]
v2: [  2 123]

Answer:
Yes, the last element in v1 is also changed to 123.
Why? Because v2 is a VIEW of v1, not a copy.
Basic indexing (slicing) creates a view that points to the same memory.
When you modify v2, you're modifying the underlying data that v1 also references.
